# -*- coding: utf-8 -*-
"""Streamlit_Interface.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uneKjPA9JFKE0GzQd1TQ2e02dTat3V9D
"""

# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1N2u1zJKSIAVBIVn9UJrZUUqnMWTy7CiO
"""

import streamlit as st
import openai
import numpy as np
from PyPDF2 import PdfReader
from chromadb.config import Settings
from chromadb.utils import embedding_functions
import chromadb
import pandas as pd
import ast
from PIL import Image

# Initialize ChromaDB client
client = chromadb.PersistentClient(path="/tmp/chromadb")
collection_name = "resource_embeddings_collection"

# Initialize OpenAI client
openai.api_key='your_key'

# Set page config for white background
st.set_page_config(
    page_title="Resource Finder",
    page_icon="🔍",
    layout="wide",
    initial_sidebar_state="expanded"
)

# Custom CSS for styling
st.markdown("""
    <style>
        .stApp {
            background-color: white;
        }
        /* Style for tabs */
        .stTabs [data-baseweb="tab-list"] {
            gap: 2px;
            background-color: white;
        }
        .stTabs [data-baseweb="tab"] {
            height: 50px;
            padding-left: 20px;
            padding-right: 20px;
            color: #1E4D8C;
            font-weight: 600;
        }
        .stTabs [aria-selected="true"] {
            background-color: #E8EFF8;
        }
        /* Style for text */
        .main-text {
            color: #1E4D8C;
            font-size: 1.1rem;
            font-weight: 500;
            margin-bottom: 1rem;
        }
        /* Style for title */
        .title {
            color: black;
            font-size: 2rem;
            font-weight: bold;
            margin-bottom: 1rem;
        }
        /* Style for section headers */
        .section-header {
            color: black;
            font-size: 1.5rem;
            font-weight: 600;
            margin-top: 1.5rem;
            margin-bottom: 1rem;
        }
        /* Style for file uploader */
        .stFileUploader {
            background-color: #F8F9FA;
            padding: 2rem;
            border-radius: 0.5rem;
            border: 2px dashed #1E4D8C;
        }
        /* Style for text area */
        .stTextArea textarea {
            background-color: white;
            color: #1E4D8C;
            border-color: #1E4D8C;
        }
        .stTextArea textarea::placeholder {
            color: #B0B0B0;
            opacity: 0.7;
        }
        .stButton>button {
        background-color: #630306;
        color: white;
        border-radius: 10px;
        padding: 10px 20px;
        font-size: 16px;
    }
    .stButton>button:hover {
        background-color: #C0392B;
    }
    .stImage {
        background-color: transparent !important;
        padding: 0 !important;
        margin: 0 !important;
    }

    </style>
""", unsafe_allow_html=True)

def initialize_collection():
    # Read and process the CSV file
    file_path = '/Users/aashisrivastava/Documents/enhanced_resources.csv'
    df_enhanced = pd.read_csv(file_path, encoding='utf-8')

    # Convert embeddings from string to list
    df_enhanced['embedding'] = df_enhanced['embedding'].apply(lambda x: ast.literal_eval(x))

    # Delete collection if it exists
    try:
        client.delete_collection(collection_name)
    except:
        pass

    # Create new collection
    collection = client.create_collection(
        name=collection_name,
        metadata={"hnsw:space": "cosine"}
    )

    # Extract data
    resource_ids = df_enhanced['resource_id'].tolist()
    descriptions = df_enhanced['enhanced_description'].tolist()
    embeddings = df_enhanced['embedding'].tolist()

    # Process in smaller batches
    batch_size = 100
    for i in range(0, len(resource_ids), batch_size):
        end_idx = min(i + batch_size, len(resource_ids))
        collection.add(
            ids=[str(id) for id in resource_ids[i:end_idx]],
            documents=descriptions[i:end_idx],
            metadatas=[{"id": str(res_id)} for res_id in resource_ids[i:end_idx]],
            embeddings=embeddings[i:end_idx]
        )

    return collection

def generate_embedding(text):
    """Generate embedding using the updated OpenAI API"""
    response = openai.Embedding.create(
        model="text-embedding-ada-002",
        input=text
    )
    return response.data[0].embedding

# Initialize or get collection
try:
    collection = client.get_collection(collection_name)
    collection = initialize_collection()
except:
    collection = initialize_collection()

# Function to extract concise query
def extract_concise_query(resume_text):
    prompt = f"""
    Analyze the following resume and summarize the candidate's work experience in a concise sentence.

    Resume: {resume_text}

    Focus on:
    - Relevant industries (e.g., Food Service, Warehousing, Logistics)
    - Avoid listing job titles or detailed skills
    - Conclude with a phrase like "is looking to upskill"

    Example: "A candidate with experience in [Industry 1], [Industry 2], and [Industry 3] is looking to upskill."
    """
    try:
        response = openai.ChatCompletion.create(
            model="gpt-3.5-turbo",
            messages=[{"role": "user", "content": prompt}],
        )
        query = response['choices'][0]['message']['content']
        return query.strip()
    except Exception as e:
        return f"Error: {e}"

def display_results(query_embedding):
    """Display matching resources based on query embedding"""
    results = collection.query(
        query_embeddings=[query_embedding],
        n_results=5
    )
    st.markdown("### 📚 Recommended Resources")
    for i, (doc, distance) in enumerate(zip(results['documents'][0], results['distances'][0])):
        similarity_score = (1 - distance)
        with st.container():
            st.markdown(f"""
                <div style="
                    padding: 1rem;
                    border-radius: 0.5rem;
                    border: 1px solid #cccccc;
                    margin: 1rem 0;
                    background-color: #ffffff;
                    box-shadow: 0 1px 3px rgba(0,0,0,0.1);
                ">
                <div style="color: #E74C3C; font-weight: bold; margin-bottom: 0.5rem;">
                    Match Score: {similarity_score:.2f}
                </div>
                <div style="color: #000000;">
                    {doc}
                </div>
            </div>
            """, unsafe_allow_html=True)

# Streamlit App - using custom title
col1, col2 = st.columns([3,1])
col1.image("/Users/aashisrivastava/Documents/RiseKit-logo.png", width=150)
col2.image("/Users/aashisrivastava/Documents/UIC-logo.png", width=150)
st.markdown('<h1 class="title">🔍 Resource Finder</h1>', unsafe_allow_html=True)
st.markdown('<p class="main-text">Find relevant resources by uploading your resume or entering a specific query.</p>', unsafe_allow_html=True)

# Create tabs for different search methods
tab1, tab2 = st.tabs(["📄 Upload Resume", "✏️ Enter Query"])

with tab1:
    st.markdown('<p class="main-text">Upload your resume (PDF or TXT format)</p>', unsafe_allow_html=True)
    uploaded_file = st.file_uploader("", type=["txt", "pdf"])

    if uploaded_file:
        try:
            # Read Resume
            if uploaded_file.type == "text/plain":
                resume_text = uploaded_file.read().decode("utf-8")
            elif uploaded_file.type == "application/pdf":
                reader = PdfReader(uploaded_file)
                resume_text = "\n".join(page.extract_text() for page in reader.pages)
            else:
                resume_text = ""

            # Generate Concise Query
            with st.spinner("Analyzing resume..."):
                concise_query = extract_concise_query(resume_text)

            # Generate Embedding for Query
            with st.spinner("Finding matching resources..."):
                query_embedding = generate_embedding(concise_query)

            if query_embedding is not None:
                # Display results with black header
                st.markdown('<h3 class="section-header">📚 Recommended Resources</h3>', unsafe_allow_html=True)
                results = collection.query(
                    query_embeddings=[query_embedding],
                    n_results=5
                )
                for i, (doc, distance) in enumerate(zip(results['documents'][0], results['distances'][0])):
                    similarity_score = (1 - distance)
                    with st.container():
                        st.markdown(f"""
                            <div style="
                                padding: 1rem;
                                border-radius: 0.5rem;
                                border: 1px solid #cccccc;
                                margin: 1rem 0;
                                background-color: #ffffff;
                                box-shadow: 0 1px 3px rgba(0,0,0,0.1);
                            ">
                            <div style="color: #E74C3C; font-weight: bold; margin-bottom: 0.5rem;">
                                Match Score: {similarity_score:.2f}
                            </div>
                            <div style="color: #000000;">
                                {doc}
                            </div>
                        </div>
                        """, unsafe_allow_html=True)

        except Exception as e:
            st.error(f"An error occurred: {str(e)}")

with tab2:
    st.markdown('<p class="main-text">Describe what kind of resources you are looking for</p>', unsafe_allow_html=True)
    user_query = st.text_area(
        "",
        placeholder="e.g. The candidate is facing financial difficulties and requires some support.",
        height=100
    )


    if st.button("Search", type="primary", use_container_width=True):
        if user_query:
            with st.spinner("Finding matching resources..."):
                query_embedding = generate_embedding(user_query)

            if query_embedding is not None:
                # Display results with the same card-style layout
                st.markdown('<h3 class="section-header">📚 Recommended Resources</h3>', unsafe_allow_html=True)
                results = collection.query(
                    query_embeddings=[query_embedding],
                    n_results=5
                )

                # Loop through the results and display each one in the same card format
                for i, (doc, distance) in enumerate(zip(results['documents'][0], results['distances'][0])):
                    similarity_score = (1 - distance)  # Convert distance to similarity score

                    with st.container():
                        st.markdown(f"""
                            <div style="
                                padding: 1rem;
                                border-radius: 0.5rem;
                                border: 1px solid #cccccc;
                                margin: 1rem 0;
                                background-color: #ffffff;
                                box-shadow: 0 1px 3px rgba(0,0,0,0.1);
                            ">
                            <div style="color: #E74C3C; font-weight: bold; margin-bottom: 0.5rem;">
                                Match Score: {similarity_score:.2f}
                            </div>
                            <div style="color: #000000;">
                                {doc}
                            </div>
                        </div>
                        """, unsafe_allow_html=True)
        else:
            st.warning("Please enter a query to search.")