# -*- coding: utf-8 -*-
"""Support_service_recommendation_system.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14BdAkxdB72GBuRTuC31CrrFYPqRtWkrr
"""

# -*- coding: utf-8 -*-
"""Risekit.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1utEq7b3p5sQ_SleqhmrMOJS9BuTapLoC
"""

from google.colab import drive
drive.mount('/content/drive')

file_path = '/content/drive/My Drive/Capstone_Group_6_IDS_560/Dataset/resources_links.csv'

import pandas as pd

# Load dataset
df = pd.read_csv(file_path)

# Select only the important columns
important_columns = [
    'title', 'description', 'keywords', 'type', 'industry',
    'barriers', 'education_level', 'background_friendly', 'experience_level',
    'disability', 'military', 'criminal_record_option_id', 'eligible',
     'remote', 'zip_code',
    'url', 'public_link',  'time_frame'
]

# Filter DataFrame to keep only the selected columns
df_cleaned = df[important_columns]

df_cleaned.info()
df_cleaned.isnull().sum()

df_cleaned.shape

unique_values = df_cleaned['type'].value_counts()
print(unique_values)

# Filtering the DataFrame to keep only 'SupportService', 'TrainingProgram', and 'Event' in the 'type' column
filtered_df = df_cleaned[df_cleaned['type'].isin(['SupportService', 'TrainingProgram', 'Event'])]

# Verify the result by checking the counts of each type after filtering
print(filtered_df['type'].value_counts())

filtered_df.info()
filtered_df.isnull().sum()

# List of columns to delete
columns_to_delete = ['keywords','zip_code'
,    'education_level', 'background_friendly', 'experience_level', 'disability',
    'military', 'criminal_record_option_id', 'eligible', 'remote', 'time_frame'
]

# Drop specified columns
df_final = filtered_df.drop(columns=columns_to_delete)

df_final.shape
df_final.isnull().sum()

!pip install openai==0.28

import os
os.environ["OPENAI_API_KEY"] =  'your_key'

import openai
import pandas as pd
import hashlib

# Function to enhance description with type, industry, and barriers
def enhance_description(title, description, resource_type, potential_barriers):
    # Generate the prompt dynamically based on resource type
    prompt = f"Enhance the description for the following resource:\n\n"
    prompt += f"Title: {title}\n"
    prompt += f"Current description: {description if description else 'No description available.'}\n"
    prompt += f"Resource type: {resource_type}\n"
    prompt += f"Barriers: {', '.join(potential_barriers)}\n\n"
    prompt += (
    "Based on the title and current description, provide an expanded and detailed description for this resource. "
    "Include a brief overview of what the resource does, specifically mentioning its main purpose, services, or mission. "
    "Incorporate additional details that would be relevant to this resource. Be sure to include any industry-specific context, "
    "the particular needs or challenges it targets, and any other inferred information that would help a reader understand its benefits. "
    "Once enhanced, identify which of the following barriers this resource specifically addresses: "
    "{', '.join(potential_barriers)}. Be specific in linking the resource's services to the relevant barriers."
)


    try:
        # Call the OpenAI API to generate an enhanced description
        response = openai.ChatCompletion.create(
            model="gpt-3.5-turbo",
            messages=[{"role": "user", "content": prompt}],
        )
        enhanced_description = response['choices'][0]['message']['content']
        return enhanced_description
    except Exception as e:
        return str(e)

# Function to generate a unique resource_id based on enhanced description
def generate_resource_id(enhanced_description):
    # Use hashlib to create a unique hash of the enhanced description
    return hashlib.md5(enhanced_description.encode()).hexdigest()

# Loop through the dataset
for index, row in df_final.iterrows():
    title = row['title']
    description = row['description']
    resource_type = row['type']
    potential_barriers = ["Housing barrier", "Mental health barrier", "Financial barrier", "Transportation barrier", "Food barrier",
                          "Identification barrier", "Government Benefits", "WiFi/Phone barrier"]

    # Enhance the description for each resource
    enhanced_description = enhance_description(title, description, resource_type, potential_barriers)

    # Generate the unique resource_id based on the enhanced description
    resource_id = generate_resource_id(enhanced_description)

    # Print the results
    print(f"Resource ID: {resource_id}")
    print(f"Description: {enhanced_description}\n")

df_enhanced_test = pd.DataFrame({
    'title': df_final[:10]['title'],
    'enhanced_description': df_final[:10].apply(lambda row: enhance_description(row['title'], row['description'], row['type'], potential_barriers), axis=1)
})
df_enhanced_test['resource_id'] = df_enhanced_test['enhanced_description'].apply(generate_resource_id)

df_enhanced_test

# Create a new DataFrame with only the relevant columns
df_enhanced = pd.DataFrame({
    'title': df_final['title'],
    'enhanced_description': df_final.apply(lambda row: enhance_description(row['title'], row['description'], row['type'], potential_barriers), axis=1)
})
df_enhanced['resource_id'] = df_enhanced['enhanced_description'].apply(generate_resource_id)

df_enhanced.to_csv('df_enhanced.csv', index=False)

import openai

# OpenAI API setup
openai.api_key = 'your_key'
# Function to generate embeddings with increased timeout
def generate_embedding(text):
    try:
        response = openai.Embedding.create(
            model="text-embedding-ada-002",
            input=text,
            timeout=200  # Increased timeout (default is 60s, set to 120s or higher)
        )
        embedding = response['data'][0]['embedding']
        return embedding
    except Exception as e:
        print(f"Error generating embedding: {e}")
        return None

# Split the dataset into smaller chunks to avoid timeouts
chunk_size = 10  # Process 10 descriptions at a time
chunks = [df_enhanced['enhanced_description'][i:i + chunk_size] for i in range(0, len(df_enhanced), chunk_size)]

# Generate embeddings for each chunk
embeddings = []
for chunk in chunks:
    chunk_embeddings = [generate_embedding(desc) for desc in chunk]
    embeddings.extend(chunk_embeddings)

df_enhanced['embedding'] = embeddings

df_enhanced.head()

# Save the enhanced DataFrame as a CSV file
df_enhanced.to_csv('enhanced_resources.csv', index=False)

!pip install chromadb

import chromadb

client = chromadb.Client()

collection_name = "resource_embeddings_collection"
collection = client.get_collection(collection_name)

# Extract resource IDs, descriptions, and embeddings
resource_ids = df_enhanced['resource_id'].tolist()
descriptions = df_enhanced['enhanced_description'].tolist()
embeddings = df_enhanced['embedding'].tolist()

# Check lengths to ensure they align
print(len(resource_ids), len(descriptions), len(embeddings))

# Insert data into ChromaDB
collection.add(
    ids=resource_ids,  # Unique identifiers for each resource
    documents=descriptions,  # Resource descriptions
    metadatas=[{"id": res_id} for res_id in resource_ids],  # Metadata: resource IDs
    embeddings=embeddings  # Resource embeddings
)

# Verify by querying
query_embedding = embeddings[0]  # Example query with the first embedding
results = collection.query(query_embeddings=[query_embedding], n_results=5)

# Display query results
print(results)

!pip install PyMuPDF

import fitz  # PyMuPDF

def extract_text_from_pdf(pdf_path):
    # Open the PDF file
    doc = fitz.open(pdf_path)

    # Extract text from all pages
    full_text = ""
    for page_num in range(len(doc)):
        page = doc.load_page(page_num)
        full_text += page.get_text()

    return full_text

# Path to your resume in Google Drive
pdf_resume_path = '/content/drive/MyDrive/Capstone_Group_6_IDS_560/Dataset/Resumes/22395.pdf'

# Extract text from the resume PDF
resume_text = extract_text_from_pdf(pdf_resume_path)
print(resume_text[:500])  # Print the first 500 characters to check

def extract_concise_query(resume_text):
    # Prompt to extract concise work experience
    prompt = f"""
    Analyze the following resume and summarize the candidate's work experience in a concise sentence.

    Resume: {resume_text}

    Focus on:
    - Relevant industries (e.g., Food Service, Warehousing, Logistics)
    - Avoid listing job titles or detailed skills
    - Conclude with a phrase like "is looking to upskill"

    Example: "A candidate with experience in [Industry 1], [Industry 2], and [Industry 3] is looking to upskill."
    """

    try:
        # OpenAI API call
        response = openai.ChatCompletion.create(
            model="gpt-3.5-turbo",
            messages=[{"role": "user", "content": prompt}],
            max_tokens=50
        )
        # Extract the response content
        query = response['choices'][0]['message']['content']
        return query.strip()
    except Exception as e:
        return f"Error: {e}"

# Example usage
resume_text = resume_text

# Extract a concise query from the resume
concise_query = extract_concise_query(resume_text)
print("Generated Concise Query for Resources:")
print(concise_query)

# Define the query text
query_text = " The candidate is struggling with mental health issues"

# Generate the embedding for the query using OpenAI's API
query_embedding = generate_embedding(concise_query)

# Use the collection you already created for resources
collection_name = "resource_embeddings_collection"
resource_collection = client.get_collection(collection_name)

# Query the resources collection using the generated query embedding
query_result = resource_collection.query(
    query_embeddings=[query_embedding],  # Query with the generated query embedding
    n_results=5  # Retrieve top 5 most similar resources
)

# Print the results
for result in query_result['documents']:
    print(result)



!pip install streamlit pyngrok

from pyngrok import ngrok

# Replace 'your-authtoken' with the actual token from the ngrok dashboard
ngrok.set_auth_token('your_token')

# Start an HTTP tunnel on the correct port (8501 for Streamlit)
public_url = ngrok.connect(8501, "http")
print("Streamlit app is live at:", public_url)